# -*- coding: utf-8 -*-
"""datasynthesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8RgSMVqLS-RiRGHNTa172fFVKpYCxgH
"""

import numpy as np
import pandas as pd
from google.colab import files

# Number of observations
observations = 10000

# Generate random data
np.random.seed(42)  # For reproducibility
temperature = np.random.normal(loc=25, scale=3, size=observations)  # Example: Mean=75, Std=5
vibration = np.random.normal(loc=0.5, scale=0.1, size=observations)  # Example: Mean=0.5, Std=0.1
pressure = np.random.normal(loc=2, scale=0.2, size=observations)  # Example: Mean=30, Std=2
conductivity = np.random.normal(loc=100, scale=15, size=observations)  # Example: Mean=100, Std=15

# Create a DataFrame
data = {
    'Temperature': temperature,
    'Vibration': vibration,
    'Pressure': pressure,
    'Conductivity': conductivity
}

df = pd.DataFrame(data)

# Save to CSV file
csv_file = 'machine_operations.csv'
df.to_csv(csv_file, index=False)

# Download the CSV file to local machine
files.download(csv_file)